// Re-export all types and constants from the shared module
export type {
  Priority,
  ColumnId,
  AgentStatus,
  AgentType,
  AgentInfo,
  Project,
  ProjectTaskCounts,
  ProjectConfig,
  ProjectPathValidation,
  RepositoryEvidence,
  RepositoryEvidenceCommit,
  RepositoryEvidenceFile,
  RepositoryEvidenceState,
  RoadmapPreview,
  RoadmapProposedTask,
  RoadmapProposedGroup,
  RoadmapExecutionMode,
  RoadmapCreationMode,
  CreateProjectRequest,
  UpdateProjectRequest,
  Task,
  TaskAttachment,
  TaskGroup,
  ReconfigureTaskGroupInput,
  TaskTemplate,
  AgentEventType,
  AgentEvent,
  ContextBudgetSnapshot,
  Column,
  WSMessage,
} from '../../../../shared/types.js';

export { VALID_TRANSITIONS, MAX_GROUP_CHILDREN, MIN_GROUP_CHILDREN } from '../../../../shared/constants.js';
